### ISSUE TITLE
TimedObservable is missing

### ISSUE THREAD

**Issue by 1fexd** [Xerus2000/mpris-java#1]
Hello,

I just tried running your test player and it failed with a missing import for `xerus.ktutil.javafx.properties.TimedObservable`, where can I get this class from?

**Comment by xeruf** [comment]
This is probably related to an updated in my personal [util project](https://github.com/xerus2000/util) which I haven't probably versioned, give me a minute :)

**Comment by xeruf** [comment]
Should be fixed now, otherwise hit me up again. Don't forget to first sync with Gradle.
